from datetime import datetime
from pathlib import Path

from pydantic import BaseModel, ConfigDict, Field, HttpUrl, field_validator


class AnalyzeRequest(BaseModel):
    """Payload for repository analysis requests."""

    repo_url: HttpUrl
    branch: str | None = Field(default=None, min_length=1, max_length=255)

    @field_validator("branch")
    @classmethod
    def normalize_branch(cls, value: str | None) -> str | None:
        if value is None:
            return None
        stripped = value.strip()
        return stripped or None


class RepoMetadata(BaseModel):
    """Subset of GitHub repository metadata used by Phase 1."""

    full_name: str
    description: str | None = None
    default_branch: str
    language: str | None = None
    size: str = "0 KB"
    stargazers_count: int = 0
    forks_count: int = 0
    open_issues_count: int = 0
    fork: bool = False
    created_at: datetime | None = None
    updated_at: datetime | None = None
    pushed_at: datetime | None = None


class TreeItem(BaseModel):
    """A Git tree entry returned by the GitHub API."""

    path: str
    mode: str | None = None
    type: str
    sha: str | None = None
    size: int | None = None
    url: str | None = None


class FilteredRepoContext(BaseModel):
    """Intermediate filtering output."""

    selected_files: list[TreeItem]
    excluded_files: list[TreeItem]
    selected_paths: list[str]
    filtered_out_paths: list[str]
    filtered_out_count: int
    selected_file_count: int
    exclusion_reasons: dict[str, list[str]] = Field(default_factory=dict)


class DocumentationFile(BaseModel):
    """Documentation file content returned in the final response."""

    path: str
    size: int | None = None
    content: str


class RepoChunk(BaseModel):
    """A bounded line-range chunk for a repository text file."""

    chunk_id: str
    start_line: int
    end_line: int
    line_count: int
    char_count: int
    content: str


class RepoChunkFileEntry(BaseModel):
    """Chunked content metadata for a single repository file."""

    path: str
    size: int | None = None
    line_count: int
    char_count: int
    chunks: list[RepoChunk] = Field(default_factory=list)


class RepoChunkIndexArtifact(BaseModel):
    """Serialized chunk index generated from selected files."""

    repo_url: str
    owner: str
    repo: str
    branch: str
    selected_file_count: int
    chunk_size_lines: int
    files: list[RepoChunkFileEntry] = Field(default_factory=list)
    created_at: datetime

    model_config = ConfigDict(json_encoders={Path: str})


class TreeSummary(BaseModel):
    """Aggregate tree counts included in the final artifact."""

    total_items: int
    total_blobs: int
    total_trees: int
    filtered_out_count: int
    selected_file_count: int


class RepoContextArtifact(BaseModel):
    """Serialized repo context generated by Phase 1."""

    repo_url: str
    owner: str
    repo: str
    branch: str
    repo_metadata: RepoMetadata
    tree_summary: TreeSummary
    selected_files: list[str]
    filtered_out_files: list[str]
    documentation_files: list[DocumentationFile]
    created_at: datetime

    model_config = ConfigDict(json_encoders={Path: str})


class AnalyzeResponse(BaseModel):
    """HTTP response returned by POST /analyze."""

    status: str
    repo_url: str
    owner: str
    repo: str
    branch: str
    repo_metadata: RepoMetadata
    tree_summary: TreeSummary
    selected_files: list[str]
    filtered_out_files: list[str]
    documentation_files: list[DocumentationFile]
    output_file: str
    repo_chunk_index_file: str | None = None
    tree_analysis_plan: dict[str, object] | None = None
    tree_analysis_output_file: str | None = None
    repository_analysis: dict[str, object] | None = None
    repository_analysis_output_file: str | None = None
    markdown_report_file: str | None = None
