// ── EvalAI product types ──────────────────────────────────────────────────────

export type EventStatus = "active" | "draft" | "completed";
export type EventType = "hackathon" | "course" | "custom";
export type ArtifactStatus = "submitted" | "pending" | "missing";

export interface EvalEvent {
  id: string;
  name: string;
  type: EventType;
  status: EventStatus;
  /** Student submission link generated by backend */
  studentSubmitUrl?: string;
  teamsTotal: number;
  teamsEvaluated: number;
  submissionDeadline: string;
  judgingDeadline: string;
  createdAt: string;
  /** Event artifact kinds from backend */
  artifacts?: string[];
  /** Wizard criteria / rubric config (shape varies by UI) */
  criteriaConfig?: Record<string, unknown>;
}

export interface ActivityItem {
  id: string;
  type: "analysis_complete" | "submission" | "judge_action" | "event_created" | "result_published";
  description: string;
  meta: string;
  time: string;
}

export interface StatCard {
  label: string;
  value: string | number;
  sub: string;
  trend?: "up" | "down" | "neutral";
}

// ── Repository analyzer types (from analyze workspace) ────────────────────────

export type RunStatus = "submitted" | "queued" | "running" | "completed" | "failed";
export type ItemStatus =
  | "pending"
  | "in-progress"
  | "completed"
  | "failed"
  | "skipped";

export interface RunSubtaskState {
  id: string;
  title: string;
  description: string;
  status: ItemStatus;
  detail?: string | null;
  badges: string[];
  activity_log: string[];
}

export interface RunPhaseState {
  id: string;
  title: string;
  description: string;
  status: ItemStatus;
  subtasks: RunSubtaskState[];
}

export interface RunEventState {
  id: number;
  timestamp: string;
  phase_id?: string | null;
  subtask_id?: string | null;
  kind: string;
  message: string;
  badges: string[];
}

export interface AnalyzeResponse {
  status: string;
  repo_url: string;
  owner: string;
  repo: string;
  branch: string;
  tree_analysis_plan?: {
    groups?: Record<string, string[]>;
  };
  repository_analysis?: {
    report_title?: string;
    executive_summary?: string;
    repository_overview?: string;
    component_summary?: string[];
    runtime_behavior?: string[];
    architecture_patterns?: string[];
    risks_and_weaknesses?: string[];
    quality_assessment?: string;
    strengths?: string[];
    intelligent_questions?: string[];
    recommended_next_steps?: string[];
    evidence_paths?: string[];
  };
  markdown_report_file?: string;
  repo_chunk_index_file?: string;
}

export interface AnalysisRunState {
  id: string;
  revision: number;
  status: RunStatus;
  request: CreateRunPayload;
  owner?: string | null;
  repo?: string | null;
  branch?: string | null;
  current_activity?: string | null;
  error?: string | null;
  phases: RunPhaseState[];
  events: RunEventState[];
  result?: AnalyzeResponse | null;
  markdown_report_content?: string | null;
  started_at?: string;
  updated_at?: string;
  completed_at?: string | null;
}

export interface CreateRunPayload {
  repo_url: string;
  branch?: string;
}

export interface PlanSubtask {
  id: string;
  title: string;
  description: string;
  status: ItemStatus;
  tools?: string[];
  activity?: string[];
}

export interface PlanTask {
  id: string;
  title: string;
  description: string;
  status: ItemStatus;
  dependencies: string[];
  subtasks: PlanSubtask[];
}

// ── EvalAI submission types ───────────────────────────────────────────────────

export type VoiceStatus = "idle" | "recording" | "processing" | "completed" | "failed";
export type VideoAnalysisStatus = "idle" | "pending" | "running" | "completed" | "failed";

export interface VoiceTranscriptSegment {
  text: string;
  start?: number | null;
  end?: number | null;
}

export interface VoiceTranscriptArtifact {
  session_id: string;
  event_id?: string | null;
  submission_id?: string | null;
  full_transcript: string;
  segments: VoiceTranscriptSegment[];
  provider: string;
  model: string;
  created_at: string;
  output_file?: string | null;
}

export interface Submission {
  id: string;
  eventId: string;
  teamName: string;
  repoUrl: string;
  branch?: string;
  runId?: string;
  run: AnalysisRunState;
  workerSubmissionId?: string;
  analysisJobId?: string;
  pptFileName?: string;
  videoFileName?: string;
  videoObjectKey?: string;
  videoAnalysisJobId?: string;
  videoAnalysisStatus?: VideoAnalysisStatus;
  videoAnalysisResult?: WorkerVideoAnalysisJob | null;
  voiceStatus?: VoiceStatus;
  voiceTranscript?: VoiceTranscriptArtifact | null;
  createdAt: string;
}

export interface RubricCriterionInput {
  category: string;
  description: string;
  max_score: number;
}

export interface WorkerArtifactInput {
  kind: "ppt" | "video" | "attachment";
  object_key: string;
  file_name?: string;
  content_type?: string;
  size_bytes?: number;
}

export interface WorkerSubmissionResponse {
  id: string;
  status: RunStatus;
  queued: boolean;
}

export interface WorkerFeedbackReport {
  summary?: string | null;
  raw_result?: {
    repository?: AnalyzeResponse & {
      error?: string;
      skipped?: boolean;
      reason?: string;
    };
    ppt?: {
      ppt_summary?: string;
      criteria_scores?: Array<{
        category: string;
        score: number;
        comment?: string;
      }>;
      skipped?: boolean;
      reason?: string;
      error?: string;
    };
    video?: {
      raw_output?: string;
      parsed?: WorkerVideoAnalysisJob["parsed"] | null;
      skipped?: boolean;
      reason?: string;
      error?: string;
    };
    final_grading?: {
      overall_score?: number;
      overall_max_score?: number;
      overall_reasoning?: string;
      criterion_grades?: Array<{
        criterion: string;
        score: number;
        max_score: number;
        reasoning: string;
        evidence?: string[];
      }>;
      key_strengths?: string[];
      key_improvements?: string[];
      evidence_summary?: string[];
      confidence?: string | null;
      limitations?: string | null;
    };
    final_grading_status?: {
      status?: "queued" | "running" | "completed" | "failed";
      error?: string | null;
    };
  } | null;
  scores: Array<{
    category: string;
    score: number;
    max_score?: number | null;
    comment?: string | null;
  }>;
}

export interface WorkerSubmissionDetail {
  id: string;
  event_id?: string | null;
  team_name: string;
  repo_url?: string | null;
  branch?: string | null;
  status: RunStatus;
  error_message?: string | null;
  feedback?: WorkerFeedbackReport | null;
  artifacts: Array<{
    id: string;
    kind: string;
    bucket: string;
    object_key: string;
    file_name?: string | null;
    content_type?: string | null;
    size_bytes?: number | null;
    status: string;
  }>;
  created_at: string;
  updated_at: string;
}

export interface WorkerVideoAnalysisStartResponse {
  submission_id: string;
  job_id: string;
  job_type:
    | "submission_analysis"
    | "git_analysis"
    | "ppt_analysis"
    | "video_analysis"
    | "final_grading_analysis";
  status: "pending" | "queued" | "running" | "completed" | "failed";
  queued: boolean;
  sqs_message_id?: string | null;
}

export interface WorkerVideoAnalysisJob {
  job_id: string;
  status: "pending" | "queued" | "running" | "completed" | "failed";
  job_type?:
    | "submission_analysis"
    | "git_analysis"
    | "ppt_analysis"
    | "video_analysis"
    | "final_grading_analysis";
  submission_id?: string;
  attempts?: number;
  video_path?: string | null;
  created_at: string;
  updated_at: string;
  raw_output?: string | null;
  parsed?: {
    summary?: string;
    rubric?: Array<{
      id?: string;
      score?: string;
      evidence?: string;
      timestamps?: string;
    }>;
    feature_coverage?: Array<{
      feature?: string;
      status?: string;
      evidence?: string;
    }>;
    gaps_and_risks?: string[];
    limitations?: string;
  } | null;
  error?: string | null;
}
