import type { EvalEvent, ActivityItem } from "./types";

export const MOCK_EVENTS: EvalEvent[] = [
  {
    id: "evt-1",
    name: "Spring Hackathon 2025",
    type: "hackathon",
    status: "active",
    teamsTotal: 42,
    teamsEvaluated: 18,
    submissionDeadline: "2025-04-10",
    judgingDeadline: "2025-04-15",
    createdAt: "2025-03-01",
  },
  {
    id: "evt-2",
    name: "CS Capstone — Batch A",
    type: "course",
    status: "active",
    teamsTotal: 14,
    teamsEvaluated: 14,
    submissionDeadline: "2025-03-28",
    judgingDeadline: "2025-04-05",
    createdAt: "2025-02-15",
  },
  {
    id: "evt-3",
    name: "AI Build Week",
    type: "hackathon",
    status: "draft",
    teamsTotal: 30,
    teamsEvaluated: 0,
    submissionDeadline: "2025-05-01",
    judgingDeadline: "2025-05-07",
    createdAt: "2025-03-20",
  },
  {
    id: "evt-4",
    name: "Product Design Sprint",
    type: "custom",
    status: "draft",
    teamsTotal: 20,
    teamsEvaluated: 0,
    submissionDeadline: "2025-04-20",
    judgingDeadline: "2025-04-25",
    createdAt: "2025-03-22",
  },
  {
    id: "evt-5",
    name: "Winter Hackathon 2024",
    type: "hackathon",
    status: "completed",
    teamsTotal: 38,
    teamsEvaluated: 38,
    submissionDeadline: "2024-12-10",
    judgingDeadline: "2024-12-15",
    createdAt: "2024-11-01",
  },
  {
    id: "evt-6",
    name: "ML Course — Final Projects",
    type: "course",
    status: "completed",
    teamsTotal: 22,
    teamsEvaluated: 22,
    submissionDeadline: "2024-12-20",
    judgingDeadline: "2024-12-28",
    createdAt: "2024-11-15",
  },
];

export const MOCK_ACTIVITY: ActivityItem[] = [
  {
    id: "act-1",
    type: "analysis_complete",
    description: "AI analysis completed for Team Nexus",
    meta: "Spring Hackathon 2025",
    time: "2 min ago",
  },
  {
    id: "act-2",
    type: "submission",
    description: "Team DataWave submitted their demo video",
    meta: "Spring Hackathon 2025",
    time: "18 min ago",
  },
  {
    id: "act-3",
    type: "judge_action",
    description: "Judge Dr. Chen overrode AI score for Team CodeLab",
    meta: "CS Capstone — Batch A",
    time: "1 hr ago",
  },
  {
    id: "act-4",
    type: "event_created",
    description: "Event \"AI Build Week\" created in draft",
    meta: "New event",
    time: "3 hrs ago",
  },
  {
    id: "act-5",
    type: "result_published",
    description: "Results published for Winter Hackathon 2024",
    meta: "38 teams notified",
    time: "Yesterday",
  },
];
